<div id="menu" class="default">

                <div class="floting-con"><a href="<?php echo ROOT_PATH.'admin/add-estate'; ?>" class="more">Add Estate</a></div>
            </div>

<div class="mainBodyCon">
    <!--Body right start-->
    <div class="bodyRightCon bBot">
    	<div class="bodyRightightCon_inner">    		
            <div class="bcMenuCon">
            	<div class="bcMenu">

                	<ul>
                    	<li>Estate List</li>
                   	  	
                    </ul>
                    <div class="clr"></div>
                </div>
            </div>
            
            <!--Pagination Start-->
            <?php if (count($this->paginator)):
            echo $this->paginationControl($this->paginator,'Sliding','pagination/admin_pagination.phtml');
            endif;
            ?>
           <!--Pagination End-->
           
            <?php if (count($this->paginator)): ?>
           
           <!--Data display start-->
           <div class="conHeader">
           		<div class="dataChk">&nbsp;</div>
           		<div class="dataCellH">&nbsp;</div>
                <div class="dataCellH">Title</div>
                <div class="dataCellH">Location</div>
				<div class="dataCellH2">Added Date</div>
				<div class="dataCell2">Action</div>
                
           </div>
		   <div class="clr"></div>
           
            <form autocomplete="off" name="frm_display" action="" method="post">
               <input type="hidden" name="frm_display_submit" value="1" />
           <div class="dataArea">           		
           	
               <?php foreach($this->paginator as $v): ?>
               
               
                           		<div class="dataRow0">
                	<div class="dataChk">&nbsp;</div>
                	<div class="dataCell pad10"><img src="<?php echo get_estate_image_display_path($v['ImageName']); ?>" /></div>
                    <div class="dataCell marT10"><?php echo $v['EstateTitle']; ?></div>

                    <div class="dataCell marT10"><?php echo $v['City']; ?></div>
					<div class="dataCell2 marT10"><?php echo $v['AddedDate']; ?></div>
					<div class="dataCell2 marT20"><a href="<?php echo ROOT_PATH.'admin/edit-estate/'.$v['Id']; ?>"><img src="<?php echo ROOT_PATH; ?>admin_images/edit.gif" border="0" /></a><a href="<?php echo ROOT_PATH.'admin/delete-estate/'.$v['Id'] ?>" onclick="return confirm('Do you want to delete this product?')" ><img src="<?php echo ROOT_PATH; ?>admin_images/delete.gif" /></a></div>
                    <div class="clr"></div>
                </div>
                          		
                  <?php endforeach; ?>        		
                          		
                          		
                          		
                          		
                          </div>
            </form>
           <!--Data display end-->
           
           <?php else: ?>
           
           No Result
           
           <?php endif; ?>
           
           
           <!--Pagination Start-->
            <?php if (count($this->paginator)):
            echo $this->paginationControl($this->paginator,'Sliding','pagination/admin_pagination.phtml');
            endif;
            ?>
           <!--Pagination End-->

           		   
		   
        </div>
<br class="clr"></div>
    </div>
    <!--Body right end-->
    
    <div class="clr"></div>
</div>