<div id="footer">

	<div id="copyright">
    <div style="float:left; padding:3px;"><a href="#"><img src="<?php echo ROOT_PATH; ?>images/footer_logo.gif" width="42" height="35" alt="" title="" border="0" /></a></div>
    <div style="float:left; padding:14px 10px 10px 10px;"> &copy; All Rights Reserved <?php echo date('Y'); ?> - By <a href="http://www.infoway.us" target="_blank" style="color:#772c17;">infoway</a></div>
    </div>
    
    
    <ul class="footer_menu">
    	<li><a href="<?php echo ROOT_PATH; ?>" class="nav_footer">  Home </a></li>
        <li><a href="<?php echo ROOT_PATH.'estate-list/sell'; ?>" class="nav_footer">  Selling Homes </a></li>
        <li><a href="<?php echo ROOT_PATH.'estate-list/rent'; ?>" class="nav_footer">  Renting Homes</a></li>
    </ul>

</div>