<div id="header">

       <div id="logo">
        <a href="<?php echo ROOT_PATH; ?>"><img src="<?php echo ROOT_PATH; ?>images/logo.gif" width="147" height="78" alt="" title="" border="0" /></a>
       </div>
           
       <div class="banner_adds"></div>    


<div class="menu">

<ul>
<li><a href="<?php echo ROOT_PATH; ?>">Home</a></li>
<li><a href="<?php echo ROOT_PATH.'estate-list/sell'; ?>">Selling Homes</a></li>
<li><a href="<?php echo ROOT_PATH.'estate-list/rent'; ?>">Renting Homes<!--[if IE 7]><!--></a></li>
</ul>

</div>


</div>